name: renpy_decompiler_backend
description: "Decompiler and CLI for the Ren'Py decompiler."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  glob: ^2.1.2

  pickle_decompiler:
    path: ../pickle_decompiler
  collection: ^1.18.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
