name: pickle_decompiler
description: 'Decompiles Python pickles into Dart objects.'
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.4 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
