name: renpy_decompiler_gui
description: "Visualize/decompile/export .RPA and .RPYC files"
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  mime: ^1.0.4
  just_audio: ^0.9.36
  just_audio_mpv: ^0.1.7
  just_audio_windows: ^0.2.0
  rxdart: ^0.27.7
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  file_picker: ^8.0.1

  pickle_decompiler:
    path: ../pickle_decompiler
  renpy_decompiler_backend:
    path: ../renpy_decompiler_backend
  package_info_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  hash: ^1.0.4
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "logo.png"
  adaptive_icon_monochrome: "logo_monochrome.png"
  min_sdk_android: 16
  windows:
    generate: true
    image_path: "logo.png"
    icon_size: 256
